### ISSUE TITLE
imgError is not defined [Firefox]

### ISSUE THREAD

**Issue by MatthewKosloski** [rickymetz/duotonegenerator#1]
Hey!  I tried to use your web app in the latest version of Firefox (version 61) and got the following error:

```
ReferenceError: imgError is not defined
```

Click [here](https://i.imgur.com/23fIAC0.png) to view a screenshot of the error.  Also, notice the weird spacing between elements on the sidebar.

**Comment by rickymetz** [comment]
Oh, that was where I was going to add in error handling. I forgot to build out that function, I'll remove it.

>Also, notice the weird spacing between elements on the sidebar.

Turns out `height: 100%` for flex elements displays different in webkit vs gecko, changed it to `height: auto` and it seems to work.

Thank you for the report @MatthewKosloski !

**Comment by rickymetz** [comment]
Closed by ca8c25c6b08300503c24f81a383f3d1b6e875aa2
